<?php /** @var $this \Messenger\Model\Core\View */?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?php echo empty($title) ? '' : $title; ?></title>

    <link rel="shortcut icon" href="<?php echo $this->getUrl()->addImage('favicon.ico')?>">

    <link rel="stylesheet" type="text/css" href="<?php echo $this->getUrl()->addCss('bootstrap.min.css')?>">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getUrl()->addCss('messenger.css')?>">
    <?php if (!empty($css) && is_array($css)) : ?>
        <?php foreach ($css as $cssFile) : ?>
            <link rel="stylesheet" type="text/css" href="<?php echo $this->getUrl()->addCss($cssFile)?>">
        <?php endforeach; ?>
    <?php endif; ?>

    <script type="text/javascript" src="<?php echo $this->getUrl()->addJs('jquery.min.js')?>"></script>
    <script type="text/javascript" src="<?php echo $this->getUrl()->addJs('bootstrap.min.js')?>"></script>
    <?php if (!empty($js) && is_array($js)) : ?>
        <?php foreach ($js as $jsFile) : ?>
            <link rel="stylesheet" type="text/css" href="<?php echo $this->getUrl()->addJs($jsFile)?>">
        <?php endforeach; ?>
    <?php endif; ?>
</head>
<body>

<?php echo empty($menu) ? '' : $menu; ?>

<div class="container theme-showcase" role="main">

    <?php echo empty($content) ? '' : $content; ?>

</div>

</body>
</html>